import { Router } from 'express';
import { adminRouter } from '@/routes/admin.routes.js';
import { authRouter } from '@/routes/auth.routes.js';
import { budgetRouter } from '@/routes/budget.routes.js';
import { categoryRouter } from '@/routes/category.routes.js';
import { cronRouter } from '@/routes/cron.routes.js';
import { habitsRouter } from '@/routes/habits.routes.js';
import { healthRouter } from '@/routes/health.routes.js';
import { materialRouter } from '@/routes/material.routes.js';
import { notificationRouter } from '@/routes/notification.routes.js';
import { plannerRouter } from '@/routes/planner.routes.js';
import { reminderRouter } from '@/routes/reminder.routes.js';
import { reviewRouter } from '@/routes/review.routes.js';
import { statisticsRouter } from '@/routes/statistics.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/categories', categoryRouter);
apiRouter.use('/materials', materialRouter);
apiRouter.use('/reminders', reminderRouter);
apiRouter.use('/reviews', reviewRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/statistics', statisticsRouter);
apiRouter.use('/planner', plannerRouter);
apiRouter.use('/habits', habitsRouter);
apiRouter.use('/budget', budgetRouter);
apiRouter.use('/internal/cron', cronRouter);
