import { Router } from 'express';
import { adminRouter } from '@/routes/admin.routes.js';
import { authRouter } from '@/routes/auth.routes.js';
import { categoryRouter } from '@/routes/category.routes.js';
import { contactRouter } from '@/routes/contact.routes.js';
import { cronRouter } from '@/routes/cron.routes.js';
import { dailyTaskRouter } from '@/routes/dailyTask.routes.js';
import { financeRouter } from '@/routes/finance.routes.js';
import { healthRouter } from '@/routes/health.routes.js';
import { materialRouter } from '@/routes/material.routes.js';
import { notificationRouter } from '@/routes/notification.routes.js';
import { noteRouter } from '@/routes/note.routes.js';
import { nutritionRouter } from '@/routes/nutrition.routes.js';
import { reminderRouter } from '@/routes/reminder.routes.js';
import { rhythmRouter } from '@/routes/rhythm.routes.js';
import { reviewRouter } from '@/routes/review.routes.js';
import { statisticsRouter } from '@/routes/statistics.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/contact', contactRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/categories', categoryRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/tasks', dailyTaskRouter);
apiRouter.use('/materials', materialRouter);
apiRouter.use('/notes', noteRouter);
apiRouter.use('/nutrition', nutritionRouter);
apiRouter.use('/rhythm', rhythmRouter);
apiRouter.use('/reminders', reminderRouter);
apiRouter.use('/reviews', reviewRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/statistics', statisticsRouter);
apiRouter.use('/internal/cron', cronRouter);
